name: lesson_3_homework
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # core
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # database
  shared_preferences: ^2.2.0
  drift: ^2.10.0
  sqlite3_flutter_libs: ^0.5.15

  # generators
  json_annotation: ^4.8.1

  # http
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1

  # widgets
  html: ^0.15.4

  # other
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  collection: 1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # database
  drift_dev: ^2.10.0

  # generators
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  # other
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
