name: lesson_3_homework
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # core
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # widgets
  html: ^0.15.4

  # http
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1

  # generators
  json_annotation: ^4.8.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # generators
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
